___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

#### 1. Import NumPy as np

In [25]:
import numpy as np


#### 2. Create an array of 10 zeros 

In [27]:
test = np.zeros(10)
test


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# DON'T WRITE HERE

#### 3. Create an array of 10 ones

In [28]:
test = np.zeros(10) + 1
test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# DON'T WRITE HERE

#### 4. Create an array of 10 fives

In [29]:
test = np.zeros(10) + 5
test

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
# DON'T WRITE HERE

#### 5. Create an array of the integers from 10 to 50

In [31]:
test = np.arange(10, 51)
test


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
# DON'T WRITE HERE

#### 6. Create an array of all the even integers from 10 to 50

In [32]:
test = np.arange(10, 51, 2)
test

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
# DON'T WRITE HERE

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
test = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
test

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# DON'T WRITE HERE

#### 8. Create a 3x3 identity matrix

In [34]:
test = np.eye(3)
test


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# DON'T WRITE HERE

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [37]:
test = np.random.rand(1)
test


array([0.9521612])

In [10]:
# DON'T WRITE HERE

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [38]:
test = np.random.randn(25)
test


array([-0.17925163, -0.98252991, -0.3594536 , -0.15514684, -0.99554466,
        2.06933573,  1.21158213,  0.50196779, -0.18851755, -0.85540263,
        0.43679716, -0.10677161, -0.9634763 , -1.37094875,  0.83077362,
        0.5218341 ,  1.78374201, -1.00179133,  0.23151319, -0.97361285,
        2.3508822 ,  0.23811532,  2.30497123,  2.18453714,  0.46091772])

In [11]:
# DON'T WRITE HERE

#### 11. Create the following matrix:

In [12]:
# DON'T WRITE HERE

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
# DON'T WRITE HERE

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [14]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [15]:
# CODE HERE


In [16]:
# DON'T WRITE HERE

#### 14. Write code that reproduces the output shown below.

In [17]:
# DON'T WRITE HERE

#### 15. Write code that reproduces the output shown below.

In [18]:
# DON'T WRITE HERE

#### 16. Write code that reproduces the output shown below.

In [19]:
# DON'T WRITE HERE

#### 17. Write code that reproduces the output shown below.

In [20]:
# DON'T WRITE HERE

## NumPy Operations

#### 18. Get the sum of all the values in mat

In [21]:
# DON'T WRITE HERE

#### 19. Get the standard deviation of the values in mat

In [22]:
# DON'T WRITE HERE

#### 20. Get the sum of all the columns in mat

In [23]:
# DON'T WRITE HERE

## Bonus Question

We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

# Great Job!